### PR TITLE
Provide Bidi structured text support to MessageFormat (part 2)

### LINKED ISSUE #539: Message formatting dependant on base text direction (Bidi support)
Issue of message formatting constitutes quite a challenge from Bidi perspective.
The primary consideration is, in which text direction message is supposed to be displayed.(in DOM model, the HTML element text direction is controlled either by 'dir' attribute or by 'direction' css style) 

For detailed explanation of what base text direction term means please see, for instance, pages 5-9 of the following reference document.
https://docs.google.com/document/d/1dDrSwimrQbpbXybhMYDEiJXLeeqvelnY4cc8HeCP1Nk/edit?usp=sharing

1. Let us consider for illustration the parametrized message:
Globalize.loadMessages({he: {
    error: "THE FILE {0} HASN'T BEEN FOUND",
}});
where upper case stands for Arabic/Hebrew.
Now if file pathe which is going to substitute parameter {0} is in English (like c:\file.txt) and this whole formatted message is supposed to be displayed in left-to-right text direction, the display will be senceless - the reading will be unintelligible.
Globalize("he").messageFormatter("error")("c:\file.txt");

2. In addition to the aforementioned 'use case', there is another typical usage of message formatting (let us call it bread crumb pattern) that may constitute a problem from base text direction prespective, although it may be viewed as a particular sub-case of parametric message.
Let us consider the following message (as is expected to be displayed):
Globalize.loadMessages({he: {
    breadcrumb: "{0} >> {1} >> {2}",
}});

Even if formatted message with substitutions is supposed to be displayed in left-to-right text direction, the outcome will be rather unpredictable depending on substituting text as follows: (upper case stands for Arabic/Hebrew characters, lower for English)

Globalize("he").messageFormatter("breadcrumb")([ "first", "second", "third" ])
will produce on left-to-right display: "first >> second >> third"

Globalize("he").messageFormatter("breadcrumb")([ "FIRST", "SECOND", "THIRD" ])
will produce on left-to-right display: "THIRD << SECOND << FIRST"

Globalize("he").messageFormatter("breadcrumb")([ "first", "SECOND", "THIRD" ])
will produce on left-to-right display: "first >> SECOND << THIRD"
(please note the order of substitutions on display as well as hectic directionality of <<)
In case like 'breadcrumb' the proper segment isolation is required, which may be only achived by using Unicode control characters (aka. UCC)
UCC are to be used in order to cope with the first kind of problems described above. 

The proposal is to augment the 'messageFormatter' (and 'formatMessage') API with
additional parameter - base text direction, and insert appropriate UCC into resultant
formatted string in order to resolve 2 kinds of above mentioned problems.
The base text direction parameter (either 'ltr' or 'rtl') will match the text direction in which the returned string is supposed o be displayed.

### PR DESCRIPTION
**Pull request by rxaviers**
This is a continuation of PR #599.

Fixes #539 
Ref #599 

Breaking change.

### CODE REVIEW

**Comment by rxaviers** [comment]
cc @ashensis @tomerm

**Comment by rxaviers** [comment]
The BiDi support itself is entirely implemented in https://github.com/SlexAxton/messageformat.js/pull/128 and https://github.com/SlexAxton/messageformat.js/pull/129. Therefore, this PR is overall quite simple: it's about updating messageformat.js to the corresponding updated version, adding one argument (`options`) to the message formatter methods, and updating the documentation and tests accordingly.

The API changes are shown below:

```diff
The easy API change:
- .messageFormatter( path ) ➡ function( [variables] )
+ .messageFormatter( path [, options] ) ➡ function( [variables] )

The harder API change:
- .formatMessage( path [, variables ] )
+ .formatMessage( path [, variables, options ] )
```

Although the inclusion of the referred `options` argument is somewhat simple, it could represent a challenge for the `formatMessage` API without the following breaking change:

```javascript
formatter = Globalize( "en" ).messageFormatter( "hello" );
 
// Numbered variables using Array.
formatter([ "Wolfgang", "Amadeus", "Mozart" ]);
// > "Hello, Wolfgang Amadeus Mozart"
 
// Numbered variables using function arguments. (NO LONGER SUPPORTED AFTER THIS CHANGE)
formatter( "Wolfgang", "Amadeus", "Mozart" );
// > "Hello, Wolfgang Amadeus Mozart"
```

Please, does anyone (cc @jquery/globalize) have any objection or different suggestion?

**Comment by jzaefferer** [comment]
Breaking compat on `...arguments` seems fine, but should combine that with a major version bump.

As for the implementation, the diff here looks good to me. I'm only missing a test that covers the example from the documentation, something with RTL.

**Comment by tomerm** [comment]
@ashensis is it something we can provide ? I refer to tests. Many thanks in advance.

**Comment by rxaviers** [comment]
If I recall correctly, @ashensis has some issues with his text editor to include that RTL text in the test file, therefore I've included it via 7f42082 fixup.

I need @tomerm or @ashensis to review my update and confirm if the test expected value is correct.

**Comment by jzaefferer** [comment]
I see, though that's not quite what I was looking for. You've got this in the new docs: https://github.com/jquery/globalize/pull/623/files#diff-7735b03e77c86b04c1be49471c334107R231

I'd like to see that in a unit or functional test as well.

**Comment by ashensis** [comment]
1. RTL text in 7f42082 fixup confirmed to be OK.
2. Regarding @jzaefferer remark on lacking uni test that covers the example from the documentation, both message-formatter.js and format-message.js contains such tests.

**Comment by rxaviers** [comment]
> // > "Third << Second << First"

I see. I believe the engine that interprets the BiDi marks will render the string as that, but the returned String itself isn't reverted. Therefore, the doc needs fix.

@tomerm @ashensis could you please confirm?

**Comment by ashensis** [comment]
Indeed , the string itself isn't reverted, the "Third << Second << First" sequence demonstrates how the text will look on display.

**Comment by rxaviers** [comment]
I am closing all old (and stalled) PRs

**Pull request closed without merging**
