### PR TITLE
Number: Fix parser to handle empty string

### LINKED ISSUE #682: New v1.2.* returns 0 when number-parsing empty strings
See 

http://stackoverflow.com/questions/41748476/globalize-bug-in-new-v1-2-parsing-empty-string-returns-0

In short, there seems to be a regression in v1.2.* in that empty strings are now number parsed to 0 instead of NaN This seems rather non-intuitive, and I can't imagine it's intentional.

### PR DESCRIPTION
**Pull request by rxaviers**
Fixes #682
Ref #292
Ref #353

### CODE REVIEW

**Comment by jzaefferer** [comment]
That's a lot of regular expressions that are pretty hard to read. I can't tell where in the tokenizer update you're now handling the empty string. But it seems to be working, so, up to you to add more comments or not.

**Comment by rxaviers** [comment]
Yeap, the regexps are starting to go crazy. The explanation I have is:
- https://github.com/rxaviers/globalize/blob/b1745f1babf7fb9d5a7bcb8293405c3682b0523c/src/number/parse-properties.js#L101 which corresponds to https://github.com/rxaviers/globalize/blob/b1745f1babf7fb9d5a7bcb8293405c3682b0523c/src/number/parse-properties.js#L138-L139
- The extra part has its own comment https://github.com/rxaviers/globalize/blob/b1745f1babf7fb9d5a7bcb8293405c3682b0523c/src/number/parse-properties.js#L141-L143

Any suggestion how to improve that please?

**Comment by jzaefferer** [comment]
I've looked at those, but barely understand anything. I think I'd have to spend a few hours to understand the context, probably not quite worth it as this point.

So, good to go :-)

**Comment by rxaviers** [comment]
Sure thanks for the review

**Pull request merged**
