### PR TITLE
Update metadata and polish testing and linting config

### PR DESCRIPTION
**Pull request by Krinkle**
* Update URLs to github.com/globalizejs.
* Add `package-lock.json` file.
* Remove redundant `grunt-cli`.
* Switch from JSHint+JSCS to ESLint, and make `test/` pass.
* Build: Remove or mark newly-found unused variables.

See individual commit messages for more details and smaller diff.

### CODE REVIEW

**Comment by rxaviers** [comment]
Thanks for the updates @Krinkle!

**Review by rxaviers — APPROVED** [review]

**Comment by rxaviers** [comment]
At the moment, I am waiting for the CLA to pass for merging it.

**Comment by Krinkle** [comment]
@rxaviers Oops, done!

**Comment by rxaviers** [comment]
Thanks

**Pull request merged**
