### PR TITLE
Numbers: support compact mode (2/2)

### PR DESCRIPTION
**Pull request by rxaviers**

### CODE REVIEW

**Comment by rxaviers** [comment]
Updates:
- Improved documentation
- Squashed and rebased

**Comment by rxaviers** [comment]
Much thanks to @sieverk 🎉

**Comment by sieverk** [comment]
Nah, sorry about all the holdup on my end. Much thanks for finishing up and merging!

**Comment by necolas** [comment]
Please could a new version of the library including these changes be published?

**Comment by paularmstrong** [comment]
@rxaviers can we get a new version published with this, please?

**Comment by rxaviers** [comment]
@necolas and @paularmstrong, unfortuntely this feature isn't present in the [examples](https://github.com/globalizejs/globalize/tree/master/examples) and compiler tests ([[1]](https://github.com/globalizejs/globalize/tree/master/test/compiler) and [[2]](https://github.com/globalizejs/globalize-compiler/tree/master/test)). Can you help me get these updated? I can create an alpha release now to help it.

**Comment by rxaviers** [comment]
+ globalize@1.4.0-alpha.0

**Comment by necolas** [comment]
At the moment we are forking several globalize packages. It would be great if you could publish non-alpha versions anyway and update examples, etc., later.

**Comment by rxaviers** [comment]
I feel your pain by working with forks, but an actual globalize release is supposed to be stable, including complete tests and docs/examples.

**Comment by diligiant** [comment]
@necolas I know the feeling ;( How about I do what's needed tomorrow morning (Europe) so @rxaviers can release 1.4 tomorrow?

**Comment by necolas** [comment]
> I feel your pain by working with forks

Twitter works with forks because it allows the team to make progress. Getting patches merged and released upstream here has been very slow so far :)

**Comment by rxaviers** [comment]
> Getting patches merged and released upstream here has been very slow so far :)

Good old days where jQuery Foundation sponsored dedicated work for its projects, but the Foundation broke. Even working at PayPal with i18n (who uses globalize too), there's no immediate budget to work on the open source by itself. Instead it also has its forks and wrappers.

Thank you for your continued effort to bringing patches and improvements upstream for the greater good. I also believe on it and try my best to find time among the pile of growing work (and life stack) to get this moving. Unfortunate my best response for now is that all help is appreciated.

**Comment by necolas** [comment]
I'm concerned to hear that PayPal has also forked these projects and isn't contributing back upstream

**Comment by rxaviers** [comment]
PayPal contributed back timezone support and dateToParts.

**Pull request merged**
