### PR TITLE
LICENSE: Add MIT header

### PR DESCRIPTION
**Pull request by rxaviers**
@scottgonzalez @kborchers please can you confirm this update is ok? Thanks

### CODE REVIEW

**Comment by kborchers** [comment]
Not sure how we missed this before but the copyright line needs to be updated to

`Copyright JS Foundation and other contributors, https://js.foundation`

Otherwise the addition of the MIT header LGTM

**Comment by rxaviers** [comment]
> Copyright JS Foundation and other contributors, https://js.foundation

Updated in https://github.com/rxaviers/globalize/tree/license-mit, though it seems like github hasn't synced my updates in this PR yet (weird, never saw that before)

**Comment by kborchers** [comment]
Wow, that is very strange 😕

**Comment by rxaviers** [comment]
There we go, now it's synced.

**Comment by scottgonzalez** [comment]
I know this was already merged, but since I was tagged, I figured I'd still leave my feedback.

I personally avoid doing this type of labeling because we've gone through the effort of informing users that even though this package itself is released under the terms of the MIT license, it has portions of its own code, as well as dependencies, that are released under different licenses. If you want to include the heading of "The MIT License (MIT)", I would suggest adding that on L14 rather than L1.

**Comment by rxaviers** [comment]
Makes sense Scott, I'm pushing an amend commit soon.

**Comment by rxaviers** [comment]
Updated in d01e049

**Pull request merged**
