### PR TITLE
Updated README no currency parsing yet

### PR DESCRIPTION
**Pull request by goatandsheep**
Updated readme to reflect current state of [currency parsing ticket](https://github.com/globalizejs/globalize/issues/364)

### CODE REVIEW

**Comment by rxaviers** [comment]
Thanks! I'm waiting the above become green to merge. Let me know if you need help fixing the commit message.

**Comment by goatandsheep** [comment]
@rxaviers is it even possible to change a commit message or should I open a new PR?

**Comment by rxaviers** [comment]
CLA is fine, I can tweak the commit message, no problem.

**Comment by rxaviers** [comment]
Merged in 838bdd7. Thanks!

**Pull request closed without merging**
