### PR TITLE
Date: Olson-timezone-support (real 'z', 'v', 'V') and options.timeZone

### LINKED ISSUE #340: Date: Olson-timezone-support (real `z`, `v`, `V` and more)
See #202.

**Format**

_Native Date Object_ (implemented)
- Zone `z` - fall back to O
- Zone `Z`
- Zone `O`
- Zone `X`
- Zone `x`

_Extended Olson-timezone-supported Date Object_
- [x] Zone `z`
- [x] Zone `Z`
- [x] Zone `O`
- [x] Zone `v`
- [x] Zone `V`
- [x] Zone `X`
- [x] Zone `x`

**Parse**
- [x] Zone `z`
- [x] Zone `Z`
- [x] Zone `O`
- [x] Zone `v`
- [x] Zone `V`
- [x] Zone `X`
- [x] Zone `x`

---

Docs:
- [UTS TR35: Unicode LDML Part 4: Dates](http://www.unicode.org/reports/tr35/tr35-dates.html#Supplemental_Time_Zone_Data)
- [CLDR Translation Guidelines: Time Zones](http://cldr.unicode.org/translation/timezones)

### LINKED ISSUE #453: Question - Localized Date Format by Timezone
Maybe I am missing it, but I don't see a way to get the Localized DateTime Format based on the Time Zone.
Having:
var testDate = new Date(Date.UTC( 2014, 2, 21, 0, 0, 0 ));
formatDate( testDate, { datetime: "medium" });

and for 2 different Time Zones get a different Output:

A) for Time Zone: America/Los_Angeles get:  
Mar 20, 2014, 5:00:00 PM

B) for America/Mexico_City get:
Mar 20, 2014, 7:00:00 PM

I didn't see a way to pass the TZ, but maybe I am missing it.
thanks

@rxaviers

### PR DESCRIPTION
**Pull request by rxaviers**
Checklist:
- [x] Normal Code
- [x] Unit tests
  - [x] test/unit/date/format.js
  - [x] test/unit/date/format-properties.js
- [x] Functional tests
  - [x] Test `options.timeZone`
- [x] Runtime code
- [x] Documentation
  - [x] `options.timeZone`
- [x] Examples
  - [x] Add `options.timeZone`
- [x] Use external [zoned-date-time](https://github.com/rxaviers/zoned-date-time/) module

Notes:
- Fixes #340 
- Fixes #453
- [x] Should merge after #700
- Original PR: #687

### CODE REVIEW

**Comment by rxaviers** [comment]
The below is wrong, it should use "British Summer Time" name instead.

```js
Globalize('en-GB').formatDate(new Date(2017,8,1), {datetime: 'full', timeZone: 'Europe/London'})
'Friday, 1 September 2017 at 04:00:00 GMT+01:00'
```

**Comment by rxaviers** [comment]
To quickly demo what's coming... I hope you like it!

```
npm install globalize@1.3.0-alpha.0 cldr-data iana-tz-data
```

```js
var Globalize = require( "globalize" );
Globalize.load( require( "cldr-data" ).entireSupplemental() );
Globalize.load( require( "cldr-data" ).entireMainFor( "en" ) );
Globalize.loadIANATimezone( require( "iana-tz-data" ) );

Globalize( "en" ).formatDate(new Date(), {datetime: "short", timeZone: "America/Los_Angeles"});
// > '3/19/17, 3:19 PM'
Globalize( "en" ).formatDate(new Date(), {datetime: "short", timeZone: "America/New_York"});
// > '3/19/17, 6:19 PM'
Globalize( "en" ).formatDate(new Date(), {datetime: "short", timeZone: "America/Sao_Paulo"});
// > '3/19/17, 7:19 PM'
Globalize( "en" ).formatDate(new Date(), {datetime: "short", timeZone: "Europe/Berlin"});
// > '3/19/17, 11:19 PM'

Globalize( "en" ).formatDate(new Date(), {datetime: "full", timeZone: "America/Los_Angeles"});
// > 'Sunday, March 19, 2017 at 3:19:22 PM Pacific Daylight Time'
Globalize( "en" ).formatDate(new Date(), {datetime: "full", timeZone: "America/New_York"});
// > 'Sunday, March 19, 2017 at 6:19:22 PM Eastern Daylight Time'
Globalize( "en" ).formatDate(new Date(), {datetime: "full", timeZone: "America/Sao_Paulo"});
// > 'Sunday, March 19, 2017 at 7:19:22 PM Brasilia Standard Time'
Globalize( "en" ).formatDate(new Date(), {datetime: "full", timeZone: "Europe/Berlin"});
// > 'Sunday, March 19, 2017 at 11:19:53 PM Central European Standard Time'
```

**Comment by mattyork** [comment]
@rxaviers I LOVE YOU. We need this.

**Comment by mattyork** [comment]
Any updates on this? We need to add support for timezones in the next few weeks.

**Comment by mattyork** [comment]
Globalize compiler isn't working with the alpha. Versions used:

```
    "globalize": "1.3.0-alpha.3",
    "globalize-compiler": "0.3.0-alpha.3",
    "iana-tz-data": "2017.1.0",
```
Here's the script that's failing:

```js
const ianaTzData = require('iana-tz-data');
const Globalize = require("globalize");
const cldrData = require('./vendor/cldr-data.json');
Globalize.loadIANATimeZone(ianaTzData);
Globalize.load(cldrData);
Globalize.locale("en");

const date = new Date();
const d1 = Globalize.dateFormatter({ datetime: "full" })
console.log(d1(date))

const globalizeCompiler = require('globalize-compiler');

const out = globalizeCompiler.compile([d1])
```
It fails here in the globalize compiler, failing to extract the formatter because it doesn't have the runtimeArgs. 
image

**Comment by rxaviers** [comment]
Hi @mattyork, we should have a 1.3.0 soon. 

About the issue above, Thanks for reporting it.

**Comment by rxaviers** [comment]
For the record, the fix for the dateFormatter runtime issue is here: #724

**Comment by rxaviers** [comment]
Rebased and squashed

**Comment by rxaviers** [comment]
Merged :man_dancing:

**Pull request closed without merging**
